const cases = {
  palantir: {
    kicker: 'Case study 01 / Ethical case analysis', title: "Palantir's AI in military decision-making", lede: 'A responsible AI analysis of Gotham and AIP: systems that aggregate intelligence, surface threat scores, and may influence lethal decisions.', tags: ['Aman', 'CIA 1', 'Responsible AI', 'Military AI'], original: 'originals/Palantir_AI_Military_Ethics_Report (1).pdf', contextTitle: 'From data fusion to targeting', context: 'Palantir platforms combine surveillance feeds, signals intelligence, satellite imagery, social media, and other records to create real-time operational pictures. The ethical stakes change when those systems recommend targets or guide battlefield action.', questionTitle: 'Can speed replace meaningful human judgment?', question: 'The central issue is whether an opaque, probabilistic system can participate in a lethal decision without creating a responsibility vacuum. Human authorization that cannot understand, question, or meaningfully override a recommendation is oversight in name only.', findings: [['Utilitarian ethics', 'Benefits are claimed as precision and speed, but public evidence for harm reduction is limited while civilian risk is distributed unequally.'], ['Deontological ethics', 'Opacity, lack of due process, and failure to guarantee distinction between combatants and civilians violate non-negotiable duties.'], ['Rights and care', 'The right to life, privacy, remedy, and contextual human judgment are placed behind operational tempo.'], ['Responsible AI gap', 'Fairness, accountability, transparency, privacy, safety, and human oversight are structurally incomplete.']], recommendationTitle: 'Responsibility must be designed in.', recommendation: 'Require documented human authorization at every lethal step, independent audits of accuracy and civilian harm, IHL constraints embedded in the system, and an international framework for autonomous weapons.'
  },
  prescriptions: {
    kicker: 'Case study 02 / Ethical AI model design', title: 'Rx Sentinel', lede: 'An AI system concept for detecting fake and fraudulent drug prescriptions without turning an anomaly flag into an automatic punishment.', tags: ['Aman', 'CIA 1', 'Healthcare AI', 'Human review'], original: 'originals/Ethical_AI_Fake_Prescription_Detection (1).pdf', contextTitle: 'Fraud detection with clinical context', context: 'The system analyses prescription records, doctor profiles, patient history, pharmacy logs, and scanned prescription images. It looks for over-prescribing, duplicate collection, document forgery, and pharmacy mismatches.', questionTitle: 'How do we prevent a false positive from becoming harm?', question: 'A palliative care or oncology doctor may legitimately prescribe high doses. A model trained on general data could flag that care as suspicious, discourage treatment, and create a new harm while trying to prevent another.', findings: [['Expected output', 'Risk score, flag type, document anomaly map, and a clear human-readable explanation for every alert.'], ['Fairness', 'Specialty-specific baselines must distinguish legitimate high-dose care from unusual general-practice behavior.'], ['Safety', 'False positives and false negatives need continuous monitoring and independent review before deployment.'], ['Accountability', 'The model narrows thousands of records to cases worth reviewing; it never blocks a prescription by itself.']], recommendationTitle: 'Use AI to focus attention, not make the judgment.', recommendation: 'Require trained human review, an appeals process for patients and doctors, anonymised access controls, medical-specialty context, and public reporting of error rates.'
  },
  strava: {
    kicker: 'Case study 03 / Responsible data audit', title: 'Strava data audit', lede: 'An audit of how a fitness platform turns location, health, and social data into a question of consent, surveillance, and digital inequality.', tags: ['Aman', 'Unit 2', 'Privacy', 'Data power'], original: 'originals/Strava_Responsible_Data_Audit (2).pdf', contextTitle: 'When a fitness track becomes a map of power', context: 'Strava collects GPS routes, pace, elevation, timestamps, biometrics, profiles, social content, device data, and usage signals. It also offers aggregated activity data through Strava Metro for urban planning and other uses.', questionTitle: 'Can consent be informed when aggregation changes the meaning of data?', question: 'The platform gives users privacy zones and opt-outs, but broad data purposes are accepted through bundled terms while important location visibility settings require users to discover and change defaults after signup.', findings: [['Privacy', 'A handful of location points can re-identify people, and routes can expose homes, workplaces, routines, or sensitive sites.'], ['Dark patterns', 'Default sharing, social pressure, gamification, and feature paywalls can encourage disclosure or unequal access.'], ['Data power', 'The 2018 Global Heatmap incident shows how harmless-looking activity data can reveal protected locations at scale.'], ['Digital inequality', 'Premium tools, reliable connectivity, safe outdoor access, and accurate devices shape who is represented and who benefits.']], recommendationTitle: 'Make the safest choice the easiest choice.', recommendation: 'Use private defaults, purpose-by-purpose consent, plain-language notices, stronger limits on aggregated data, and independent audits for sampling bias and representational harm.'
  },
  kargu: {
    kicker: 'Case study 04 / AI Ethics Canvas', title: 'Kargu-2 autonomous drone incident', lede: 'An analysis of the reported 2020 Libya incident, where a “fire, forget and find” capability exposed the limits of human control and attribution.', tags: ['Aman', 'CIA 3', 'Autonomous systems', 'IHL'], original: 'originals/AI_Ethics_Canvas_Aman_2460324 (1).pdf', contextTitle: 'A system that can find without a live link', context: 'The UN Panel of Experts on Libya reported that Kargu-2 loitering munitions were programmed to attack targets without requiring data connectivity between operator and munition. The report does not confirm that people were killed fully without human supervision, and that ambiguity matters.', questionTitle: 'Who is accountable when the final choice is distributed?', question: 'The manufacturer, commanders, operators, state, and regulators all shape the system, but no single actor may stand clearly behind an individual engagement. Autonomy can distribute responsibility without eliminating it.', findings: [['Direct risk', 'Misclassification may harm retreating, surrendering, wounded, or incapacitated people who should be protected under IHL.'], ['Systemic risk', 'Proliferation, escalation, training bias, and faster-than-human decision cycles can widen the harm.'], ['Accountability', 'A distributed model is needed across designer, deployer, commander, state, and regulator.'], ['Human control', 'Meaningful control means a human authorizes each lethal engagement, not only the overall mission.']], recommendationTitle: 'Keep a responsible human at the point of force.', recommendation: 'Mandate human authorization, IHL compliance testing, auditable black-box logs, geofencing, engagement windows, post-action review, and manufacturer disclosure of training data and failure modes.'
  },
  genai: {
    kicker: 'Case study 05 / CIA 3 Component 2', title: 'Generative AI digital ethics portfolio', lede: 'A portfolio presentation examining how generative systems reshape truth, creativity, authorship, persuasion, and the global ethical order.', tags: ['Aman', 'Unit 5', 'Generative AI', 'Digital ethics'], original: null, contextTitle: 'Truth and creativity in a synthetic world', context: 'Generative AI can produce convincing text, images, audio, and video at scale. That creative power supports education, accessibility, and expression, but it also creates synthetic reality, epistemic risk, misinformation, deepfakes, propaganda, and uncertainty about who authored or should be accountable for content.', questionTitle: 'How can creativity remain responsible when reality is easy to manufacture?', question: 'The ethical challenge is not only whether generated content is true. It is also who benefits from the technology, whose culture and labor are represented in its training data, who is harmed by persuasion or impersonation, and whether one universal ethical framework can fit every community.', findings: [['Synthetic reality', 'Deepfakes and persuasive generated media can weaken trust in evidence, institutions, witnesses, and public knowledge.'], ['Authorship and labor', 'Generated work raises questions about consent, copyright, attribution, creative livelihoods, and the moral status of machine-produced content.'], ['Global ethics', 'Governance must account for cultural pluralism and Global North–South asymmetries in compute, data, labor, and rule-making power.'], ['Portfolio artifacts', 'The presentation combines posters, infographics, AI-generated examples, awareness guidance, ethical analysis, reflection, and supporting references.']], recommendationTitle: 'Label, verify, disclose, and share power.', recommendation: 'Use provenance labels, consent-based datasets, human review for high-impact content, clear authorship and copyright attribution, accessible public education, and governance that includes communities affected by AI rather than only the companies building it.'
  }
};

const key = new URLSearchParams(window.location.search).get('case') || 'palantir';
const selected = cases[key] || cases.palantir;
document.title = `${selected.title} — Aman`;

document.querySelector('#case-kicker').textContent = selected.kicker;
document.querySelector('#case-title').textContent = selected.title;
document.querySelector('#case-lede').textContent = selected.lede;
document.querySelector('#case-meta').innerHTML = selected.tags.map((tag) => `<span>${tag}</span>`).join('');
if (selected.original) {
  document.querySelector('#original-link').href = `original-viewer.html?file=${encodeURIComponent(selected.original)}`;
} else {
  document.querySelector('#original-link').hidden = true;
  document.querySelector('#original-link').style.display = 'none';
}
document.querySelector('#context-title').textContent = selected.contextTitle;
document.querySelector('#context').textContent = selected.context;
document.querySelector('#question-title').textContent = selected.questionTitle;
document.querySelector('#question').textContent = selected.question;
document.querySelector('#findings').innerHTML = selected.findings.map(([title, text]) => `<div class="finding"><h3>${title}</h3><p>${text}</p></div>`).join('');
document.querySelector('#recommendation-title').textContent = selected.recommendationTitle;
document.querySelector('#recommendation').textContent = selected.recommendation;
